# Header
navbar_brand: false
menu:
  Home: index.html
  Archives: archives/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
widgets:
- about         # See also: `about_content`
- category
- tag
- tagcloud
- archive
- recent_posts
about_widget_content: >
  <p>I’ve dreamt about the future my whole life. I imagine what life
  can be like. I’m also an inventor and love gadgets. I can’t wait for
  the creative world to bring us cool new stuff and exciting new ways
  to do things, and I try to do what I can to help.</p>

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon:
twitter_id:
google_plus:
fb_admins:
fb_app_id:
